# Setup
title:            0day Engineer
tagline:          'ðŸ‘£'
description:      'Even ghosts leave footprints.'
url:              https://0day.engineer
baseurl:          ''
paginate:         2

# About and contact
author:
  name:           'Bobby Tonic'
  url:            https://twitter.com/b0bbytabl3s

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
